name: Version Bump

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Bump version and push tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        PR_TITLE="${{ github.event.pull_request.title }}"

        # Determine version type from PR title
        if [[ "$PR_TITLE" == *"[major]"* ]]; then
          VERSION_TYPE="major"
        elif [[ "$PR_TITLE" == *"[minor]"* ]]; then
          VERSION_TYPE="minor"
        else
          VERSION_TYPE="patch"
        fi

        # Bump version

        # Push tag to repository
        BASE=$(git rev-list --tags --max-count=1)
        HEAD=$(git rev-parse HEAD)
        RELEASE_NOTES=$(git log --pretty=format:"- %h %s" --abbrev-commit $BASE..$HEAD)
        git log --merges --pretty=format:"- %h %s" --grep="Merge pull request" --abbrev-commit $BASE..$HEAD
        echo "RELEASE_NOTES: ${RELEASE_NOTES}"
        npm version $VERSION_TYPE -m "release: %s"
        git push --follow-tags

#      - name: Create Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: ${{ steps.releasenotes.outputs.notes }}
#          draft: false
#          prerelease: false

